name: Validate Branch
on:
  # Enable workflow as callable from another workflow
  workflow_call:
    inputs:
      github-ref:
        description: 'Current branch head ref.'
        required: true
        type: string

# Default permissions
permissions:
  contents: read


jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch history so semantic-release can find prior tag
          ref: ${{ inputs.github-ref }}  # Checkout the branch/ref passed in

      - name: Dry Run Semantic Release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_operation_mode: true  # I.E. --noop Dry run only, no publishing

  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
      - name: Install project
        run: poetry install --with dev --no-interaction --no-root
      - name: Lint Format | Ruff
        run: poetry run ruff format --check .
      - name: Lint Check | Ruff
        run: poetry run ruff check .
      - name: Lint Typecheck | Mypy
        run: poetry run mypy --config-file pyproject.toml .

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "TODO: Add unit tests"'

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "TODO: Add integration tests"'
